dist: trusty

sudo: required

language: cpp

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
# Ruby for cucumber
- rvm use 2.5.1 --install --binary --fuzzy
- ruby --version
- gem install bundler


compiler:
- clang
- gcc
os:
- linux
- osx

matrix:
  exclude:
  - os: osx
    compiler: gcc
  include:
  - os: linux
      addons:
        apt:
          update: true
          sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-5.0
              - boost-latest
          packages:
              - gcc-7
              - g++-7
              - clang-5.0
              - libboost1.55-all-dev

before_script:
    - git submodule update --init --remote --recursive
script:
    - bash -x scripts/install_cucumber_cpp.sh
    - bash -x scripts/build_and_run_tests.sh
